postgres.url=jdbc:postgresql://postgres:5432/oplogdb
postgres.user=postgres
postgres.password=postgres

kafka.bootstrapServers=kafka:29092
kafka.topic=mongo.test.student
kafka.groupId=oplog-parser-group
